name: Python Tests

on:
    workflow_dispatch:
    push:
        branches: [development, main]
        paths:
            - connect/**
    pull_request:
        paths:
            - connect/**

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  working-directory: connect

            - name: Install ffmpeg
              run: sudo apt-get update && sudo apt-get install -y ffmpeg

            - name: Run tests
              working-directory: connect
              run: uv run --group dev pytest
